"""Agregar anio como columna

Revision ID: 04fd8b6c6785
Revises: 7afbdcd3bc03
Create Date: 2025-03-29 15:57:50.615688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fd8b6c6785'
down_revision: Union[str, None] = '7afbdcd3bc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estadisticas_delitos', sa.Column('anio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estadisticas_delitos', 'anio')
    # ### end Alembic commands ###
