"""Crear tablas iniciales

Revision ID: 5f186b9ef631
Revises: 4ee07185f9ed
Create Date: 2025-03-29 15:46:38.090177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f186b9ef631'
down_revision: Union[str, None] = '4ee07185f9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delitos',
    sa.Column('codigo_delito_snic_id', sa.Integer(), nullable=False),
    sa.Column('codigo_delito_snic_nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('codigo_delito_snic_id')
    )
    op.create_table('provincias',
    sa.Column('provincia_id', sa.String(), nullable=False),
    sa.Column('provincia_nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('provincia_id')
    )
    op.create_table('estadisticas_delitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('codigo_delito_snic_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_hechos', sa.Integer(), nullable=True),
    sa.Column('cantidad_victimas', sa.Integer(), nullable=True),
    sa.Column('cantidad_victimas_masc', sa.Integer(), nullable=True),
    sa.Column('cantidad_victimas_fem', sa.Integer(), nullable=True),
    sa.Column('cantidad_victimas_sd', sa.Integer(), nullable=True),
    sa.Column('tasa_hechos', sa.Numeric(), nullable=True),
    sa.Column('tasa_victimas', sa.Numeric(), nullable=True),
    sa.Column('tasa_victimas_masc', sa.Numeric(), nullable=True),
    sa.Column('tasa_victimas_fem', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_delito_snic_id'], ['delitos.codigo_delito_snic_id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.provincia_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_delitos')
    op.drop_table('provincias')
    op.drop_table('delitos')
    # ### end Alembic commands ###
