"""sobreescribir metodo __table_args__ en EstadisticaDelito

Revision ID: 8c785f2a3758
Revises: 373def7db1ae
Create Date: 2025-03-29 17:20:06.208324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c785f2a3758'
down_revision: Union[str, None] = '373def7db1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_estadisticas', 'estadisticas_delitos', ['provincia_id', 'codigo_delito_snic_id', 'anio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_estadisticas', 'estadisticas_delitos', type_='unique')
    # ### end Alembic commands ###
