"""Agregar columna poblacion a provincias

Revision ID: b1a9ab19d204
Revises: 52a95b22b21a
Create Date: 2025-03-31 17:36:21.181914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a9ab19d204'
down_revision: Union[str, None] = '52a95b22b21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincias', sa.Column('poblacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provincias', 'poblacion')
    # ### end Alembic commands ###
