"""Popular la base de datos mediante el archivo snic-provincias

Revision ID: bace14af3c0b
Revises: 04fd8b6c6785
Create Date: 2025-03-29 16:04:22.144256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bace14af3c0b'
down_revision: Union[str, None] = '04fd8b6c6785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
